version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  redis-cache:
    image: redis:7
    command: ["redis-server", "--save", ""]
    volumes: [redis-cache-data:/data]
    restart: unless-stopped

  redis-queue:
    image: redis:7
    command: ["redis-server", "--save", ""]
    volumes: [redis-queue-data:/data]
    restart: unless-stopped

  backend:
    image: frappe/erpnext:version-15
    command: ["bench","serve","--port","8000"]
    environment:
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$${host}}
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [mariadb, redis-cache, redis-queue]
    restart: unless-stopped

  websocket:
    image: frappe/erpnext:version-15
    command: ["node","/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [backend]
    restart: unless-stopped

  frontend:
    image: frappe/erpnext:version-15
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$${host}}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [backend, websocket]
    restart: unless-stopped
    # Coolify will proxy to this service on internal port 8080

  queue-short:
    image: frappe/erpnext:version-15
    command: ["bench","worker","--queue","short,default"]
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [backend]
    restart: unless-stopped

  queue-long:
    image: frappe/erpnext:version-15
    command: ["bench","worker","--queue","long,default,short"]
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [backend]
    restart: unless-stopped

  scheduler:
    image: frappe/erpnext:version-15
    command: ["bench","schedule"]
    volumes: [sites:/home/frappe/frappe-bench/sites]
    depends_on: [backend]
    restart: unless-stopped

volumes:
  sites:
  db-data:
  redis-cache-data:
  redis-queue-data: